apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-pac-app
    appstudio.openshift.io/component: test-triggers2
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-triggers2
  namespace: jvm-bld-test
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_stuartwdouglas_code-with-quarkus
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/stuartwdouglas/code-with-quarkus
